// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxkjnyNzVUQU9OD7DsT53wbqZydPSuqfc',
    appId: '1:64130373589:web:03a35a985dcef2b39f0f5c',
    messagingSenderId: '64130373589',
    projectId: 'fieries-1b223',
    authDomain: 'fieries-1b223.firebaseapp.com',
    storageBucket: 'fieries-1b223.appspot.com',
    measurementId: 'G-0YB2XHYQGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGuPMUmZA3M4sCT7fpWN6s6SGJXPNBbcQ',
    appId: '1:64130373589:android:aa7eec6887e7ae159f0f5c',
    messagingSenderId: '64130373589',
    projectId: 'fieries-1b223',
    storageBucket: 'fieries-1b223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxojHHsxtA5_n4yKcPU45Br7PJB4TRA4E',
    appId: '1:64130373589:ios:46851f93c750ff749f0f5c',
    messagingSenderId: '64130373589',
    projectId: 'fieries-1b223',
    storageBucket: 'fieries-1b223.appspot.com',
    iosBundleId: 'com.example.groceryAppAdmin',
  );
}
